language: go

go:
 - 1.2
 - 1.3
 - 1.4
 - tip

install:
 - go get github.com/jehiah/go-strftime
 - go get github.com/mattn/go-getopt
 - go get code.google.com/p/go-sqlite/go1/sqlite3
 - go get github.com/SlyMarbo/rss

script:
 - go build -v ffetch.go
 - go build -v fscan.go
 - go build -v fshow.go
